### ISSUE TITLE
Source build errors

### ISSUE THREAD

**Issue by swallace23** [mpasha3/trips-py#1]
Two errors for me when building from source on a Windows machine with an I5 processor: an error in setup.py and an astra-toolbox install incompatibility.

## Setup:
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\skwal\Documents\trips-py\setup.py", line 15, in <module>
          LONG_DESCRIPTION = fh.read()
                             ^^^^^^^^^
        File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2163: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed`

I solved this by just commenting out the long description lines in setup.py.

## Astra-toolbox:
`  Building wheel for astra-toolbox (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\skwal\AppData\Local\Temp\pip-install-ugcty6jo\astra-toolbox_6e744a994e6f4357944ac1165860b1c8\setup.py", line 76, in <module>
          subprocess.call(['./autogen.sh'])
        File "C:\Python312\Lib\subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      OSError: [WinError 193] %1 is not a valid Win32 application
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for astra-toolbox
  Running setup.py clean for astra-toolbox
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\skwal\AppData\Local\Temp\pip-install-ugcty6jo\astra-toolbox_6e744a994e6f4357944ac1165860b1c8\setup.py", line 76, in <module>
          subprocess.call(['./autogen.sh'])
        File "C:\Python312\Lib\subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      OSError: [WinError 193] %1 is not a valid Win32 application
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for astra-toolbox
Successfully built trips
Failed to build astra-toolbox
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (astra-toolbox)`

Which I solved by building astra-toolbox-2.2.0 from source first, which is compatible with win64.

**Comment by mpasha3** [comment]
Thank you for raising the issue and showing how you solved it. Due to updates on ASTRA, only pip install . may not work (depending on the version you install). The solution is to first successfully install ASTRA in your environment and then install TRIPs-Py.
